kind: Role
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  namespace: quay-enterprise
  name: quay-enterprise-serviceaccount
rules:
  - apiGroups: [""] # The API group "" indicates the core API Group.
    resources: ["secrets"]
    verbs: ["get", "put", "patch", "update"]
    nonResourceURLs: []
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get"]