CoreOS + Kubernetes Part by Part
--------------------------------

This guide will use Tectonic Installer to deploy a Kubernetes cluster on
Amazon AWS, then part it out, break the system, and watch it rebuild
automatically.

These instructions require a CoreOS account, and an AWS account. See
https://account.coreos.com/login[Downloading and installing Tectonic on
AWS] and link:../aws/creating-aws.md[Creating an AWS account] for more
information.

Cluster overview
~~~~~~~~~~~~~~~~

Use Tectonic Installer to deploy Kubernetes clusters. Built on top of
100% open-source Kubernetes, Tectonic offers best practices solutions to
cluster design and administration, including the following features:

* Highly Available Kubernetes: Easily deploy multiple masters and
workers of Kubernetes. Governance and User Management: Govern with RBAC
and integrate with your existing identity infrastructure: LDAP, SAML.
* Secure Networking: Set up secure networking policies with Flannel and
Calico.
* Highly Available etcd with Disaster Recovery: Deploy HA etcd with
built-in backup and restore capabilities.
* Automated Operations: Easily update and maintain your infrastructure
with CoreOS’s Automated Operations.
* Container Linux Operating System: Leverage a lightweight Linux
distribution, built for containers.
* Prometheus Monitoring and AlertManager: Monitor your cluster and
applications with Prometheus. Create alerts using Tectonic Console.
* Logging & Auditing: Audit your infrastructure, tracking all API
generated actions.

Deploy cluster
~~~~~~~~~~~~~~

First, use Tectonic Installer to deploy a cluster on AWS using a
link:../../install/aws/index.md[GUI interface], or through the command
line using link:../../install/aws/aws-terraform.md[Terraform].

Then, follow these guides to analyze, break, and watch your cluster
rebuild. * link:configure-kubectl.md[Set up kubectl] *
link:deploy-master.md[Inspect the control plane] *
link:deploy-workers.md[Inspect a Kubernetes worker node] *
link:watch-recovery.md[Break system locally and watch recovery]
