Installing Contributor Extensions for Postgres
----------------------------------------------

As of release 2.1.0, Quay Enterprise requires the
https://www.postgresql.org/docs/current/static/pgtrgm.html[pg_trgm]
extension when using PostgreSQL. This extension is part of the
https://www.postgresql.org/docs/current/static/contrib.html[Additional
Supplied Modules]. These modules can be installed with standard package
management tools on Debian and Red Hat-based systems.

Debian/Ubuntu
~~~~~~~~~~~~~

....
# apt-get update
# apt-get install postgresql-contrib
....

Red Hat/CentOS
~~~~~~~~~~~~~~

....
# yum install postgresql-contrib
....

Fedora
~~~~~~

....
# dnf install postgresql-contrib
....

Docker
~~~~~~

The https://hub.docker.com/_/postgres/[library/postgres] container
includes the `postgresql-contrib` package.

If using a container based on one of the above operating systems, modify
the container’s Dockerfile to install the postgresql-contrib package.
Containers built FROM other operating systems may need to
https://www.postgresql.org/docs/current/static/contrib.html[install the
additional modules from source].

PostgreSQL on Amazon RDS
~~~~~~~~~~~~~~~~~~~~~~~~

The `postgresql-contrib package` is included.
